const a = {
    "@react-native-community/netinfo": "^2.0.10",
    "@react-native-community/slider": "^1.1.3",
    "@react-native-community/voice": "^1.1.2",
    "react-native-actionsheet": "^2.4.2",
    "react-native-animatable": "^1.3.0",
    "react-native-base64": "0.0.2",
    "react-native-calendar-picker": "^5.22.0",
    "react-native-calendars": "^1.261.0",
    "react-native-camera": "^1.13.1",
    "react-native-collapse-view": "^1.0.0",
    "react-native-collapsible": "^1.6.0",
    "react-native-config": "^0.10.0",
    "react-native-device-info": "^0.24.3",
    "react-native-dimension": "^1.0.6",
    "react-native-document-picker": "2.2.0",
    "react-native-easy-toast": "^1.1.0",
    "react-native-elements": "^1.2.7",
    "react-native-fabric": "^0.5.2",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-file-viewer": "^1.0.15",
    "react-native-firebase": "^5.2.3",
    "react-native-flags": "^1.0.0",
    "react-native-flexi-radio-button": "^0.2.2",
    "react-native-floating-labels": "^1.1.9",
    "react-native-fs": "^2.13.3",
    "react-native-geocoder": "^0.5.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-image-marker": "^0.5.1",
    "react-native-linear-gradient": "^2.5.3",
    "react-native-loader": "^1.2.1",
    "react-native-localization": "^2.0.3",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modal": "^7.0.2",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-photo-editor": "^1.0.13",
    "react-native-progress-circle": "^2.1.0",
    "react-native-responsive-image": "^2.3.1",
    "react-native-screens": "^2.4.0",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-sectioned-multi-select": "^0.6.3",
    "react-native-simple-dialogs": "^1.0.0",
    "react-native-simple-radio-button": "^2.7.3",
    "react-native-slider": "^0.11.0",
    "react-native-snap-carousel": "3.8.4",
    "react-native-stopwatch-timer": "^0.0.21",
    "react-native-tab-view": "^1.3.1",
    "react-native-tts": "^2.0.0",
    "react-native-vector-icons": "^6.3.0",
    "react-native-video": "^5.2.0",
    "react-native-voice": "^0.2.6",
    "react-native-webview": "5.12.1",
    "react-navigation": "^3.11.0",
    "react-navigation-redux-helpers": "^2.0.6"


}

console.log(Object.keys(a));