// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  KeyLogo: require('../Images/key.png'),
  LockLogo: require('../Images/lock.png'),
  BackLogo: require('../Images/BackLogo.png'),
  LoginLogo: require('../Images/login_button.png'),
  OmnexLogo: require('../Images/Ologo.png'),
  LoginBack: require('../Images/LoginBack.png'),
  LoginBack2: require('../Images/LoginBack2.png'),
  DashboardBG: require('../Images/screens/dashboard/header.png'),
  DashBack: require('../Images/DashBack.png'),
  // Logo: require('../Images/Logo.png'),
  // usrLogo:require('../Images/screens/login/icon1.png'),
  // pwdLogo:require('../Images/screens/login/icon2.png'),
  usrLogo: require('../Images/user_icon.png'),
  pwdLogo: require('../Images/pwd_icon.png'),
  swipe: require('../Images/Swipe.png'),
  dashbgimg: require('../Images/screens/landing/bgimage.png'),
  syncImg: require('../Images/Icons/global_sync_icon.png'),
  syncCardImg: require('../Images/Icons/sync_icon.png'),
  profileImg: require('../Images/screens/dashboard/profile.png'),
  dashImg: require('../Images/screens/dashboard/dash.png'),
  settingsImg: require('../Images/screens/dashboard/settings.png'),
  helpImg: require('../Images/screens/dashboard/help.png'),
  notifImg: require('../Images/screens/dashboard/icon12x.png'),
  searchImg: require('../Images/screens/dashboard/icon22x.png'),
  refreshIcon: require('../Images/Icons/refresh1.png'),
  logoutImg: require('../Images/screens/dashboard/logout_icon2x.png'),
  downloadIconImg: require('../Images/Icons/download_icon.png'),
  cardImg: require('../Images/screens/dashboard/box_button3x.png'),
  AuditPageBG: require('../Images/AuditPage.png'),
  BackIcon: require('../Images/back_icon.png'),
  BackIconWhite: require('../Images/back_icon_white.png'),
  AuditFormButton: require('../Images/AuditFormButton.png'),
  BTN5: require('../Images/2.0/b3.png'),
  BTN1: require('../Images/2.0/b1.png'),
  BTN2: require('../Images/2.0/b2.png'),
  ChecklistBG: require('../Images/CheckListBG.png'),
  ChecklistLogo: require('../Images/check_listicon.png'),
  CheckPointBG: require('../Images/Checkpoint.png'),
  AttachIcon: require('../Images/attch_icon.png'),
  ScoreLogo: require('../Images/score.png'),
  SaveIcon: require('../Images/save_icon.png'),
  ResetIcon: require('../Images/reset_icon.png'),
  upLoad: require('../Images/sync1.png'),
  BGlayer: require('../Images/bglayer.png'),
  BGlayerHeader: require('../Images/bglayer_header.png'),
  BGlayerFooter: require('../Images/bglayer_bottom.png'),
  headerBG: require('../Images/headerRightBG.png'),
  //loadingLogo:require('../Images/screens/loading/logo.png'),
  loadingLogo: require('../Images/omnex_logo.png'),
  auditPro: require('../Images/auditPro.png'),
  ncbutton: require('../Images/nc1.png'),
  ofibutton: require('../Images/ofi1.png'),
  humanLogo: require('../Images/bg_image1.png'),
  deleteIcon: require('../Images/remove_icon_white.png'),
  Footer: require('../Images/footer.png'),
  checkLogo1: require('../Images/2.0/icon1.png'),
  checkLogo2: require('../Images/2.0/icon2.png'),
  BigAttach: require('../Images/attch_icon2x.png'),
  dashFooter: require('../Images/screens/dashboard/footer.png'),
  lineIcon: require('../Images/screens/dashboard/line_icon_white.png'),
  downloadCloud: require('../Images/Icons/download_cloud.png'),
  LOGIN: require('../Images/buttons/button4.png'),
  //LOGIN:require('../Images/Icons/button_bg.png'),
  //uploadToServerIcon:require('../Images/cloud_icon.png'),
  uploadToServerIcon: require('../Images/Icons/cloud_upload_icon.png'),
  demoLoader: '../Images/IXpO.gif',
  Fingerprint: require('../Images/Fingerprint.png'),

  // Hardcode599:require('../Images/Checkpoints/599.png'),
  // Hardcode600:require('../Images/Checkpoints/600.png'),
  // Hardcode601:require('../Images/Checkpoints/601.png'),
  // Hardcode602:require('../Images/Checkpoints/602.png'),
  ContentLoader: require('../Images/Loader/loader.gif'),
  ManIcon1: require('../Images/mon3.png'),
  ManIcon2: require('../Images/mon2.png'),
  ManIcon3: require('../Images/man_filled.png'),
  norecords: require('../Images/documents.png'),
  nodata: require('../Images/ban.png'),
  emptybox: require('../Images/emptybox.png')
};

export default images;
