import {StyleSheet, Dimensions} from 'react-native';
import {width, height} from 'react-native-dimension';
import Fonts from '../../Themes/Fonts';

let Window = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  wrapper: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
   // alignContent:'center'
  },

  // Header styles
  header1:{
    flexDirection:'row',
    justifyContent:'space-between',
    alignContent:'center'
  },
  header: {
    width: '100%',
    zIndex: 3000,
    flexDirection: 'row',
    //backgroundColor: 'white',
    padding: 5,
    alignItems: 'center',
    justifyContent: 'center',
    height: 65,
    elevation: 4,
    shadowOffset: {width: 2, height: 10},
    shadowColor: 'lightgrey',
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
  heading: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: width(70),
    height: 65,
  },
  headingText: {
    fontSize: Fonts.size.h6,
    color: '#fff',
    textAlign: 'center',
    // fontWeight:'bold',
    fontFamily: 'OpenSans-Bold',
  },
  backlogo: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    width: width(10),
    height: 65,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerDiv: {
    width: width(15),
    height: 65,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rightHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    right: 10,
    height: 80,
  },
  backgroundImage: {
    resizeMode: 'stretch',
    width: width(30),
    height: 80,
    zIndex: 0,
  },

  // Footer styles
  footer: {
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    backgroundColor: 'transparent',
    height: 65,
   // zIndex: 3000,
  },
  footerDiv: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 70,
    position: 'absolute',
    marginLeft: 25
  },
  footerLoader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  footerTextContent: {
    color: 'white',
    fontSize: Fonts.size.medium,
    fontFamily: 'OpenSans-Regular',
  },
  footerDivContent: {
    flexDirection: 'row',
    // justifyContent: 'space-between',
    // textAlign: 'center',
  },

  // Body styles
  detailsCard: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
  },
  auditPageBody: {
    flex: 1,
    zIndex: 10,
    marginLeft: 0,
    marginRight: 0,
    padding: 5,
    backgroundColor: 'white',
    justifyContent: 'flex-start',
    paddingBottom: 0,
    marginBottom: 0,
   // alignSelf: 'stretch',
   alignContent:'center',
    paddingTop: 0,
  },
  scrollView: {
    height: '80%',
    backgroundColor: 'black',
  },
  box1: {
    flex: 1,
    flexDirection: 'column',
    width: Window.width,
    height: height(8),
    backgroundColor: 'transparent',
    borderBottomColor: 'white',
    borderBottomWidth: 0.5,
  },
  box2: {
    flex: 1,
    flexDirection: 'column',
    width: Window.width,
    height: height(8),
    backgroundColor: 'transparent',
    borderBottomColor: 'white',
    borderBottomWidth: 0.5,
  },
  box3: {
    flex: 1,
    flexDirection: 'column',
    width: Window.width,
    height: height(8),
    backgroundColor: 'transparent',
    borderBottomColor: 'white',
    borderBottomWidth: 0.5,
  },
  box4: {
    flex: 1,
    flexDirection: 'column',
    width: Window.width,
    height: height(8),
    backgroundColor: 'transparent',
    borderBottomColor: 'white',
    borderBottomWidth: 0.5,
  },
  box5: {
    flex: 1,
    flexDirection: 'column',
    width: Window.width,
    height: height(8),
    backgroundColor: 'transparent',
    borderBottomColor: 'white',
    borderBottomWidth: 0.5,
  },
  box6: {
    flex: 1,
    flexDirection: 'column',
    width: Window.width,
    height: height(8),
    backgroundColor: 'transparent',
    borderBottomColor: 'white',
    borderBottomWidth: 0.5,
  },
  box7: {
    flex: 1,
    flexDirection: 'column',
    width: Window.width,
    height: height(8),
    backgroundColor: 'transparent',
    borderBottomColor: 'white',
    borderBottomWidth: 0.5,
  },
  box8: {
    flex: 1,
    flexDirection: 'column',
    width: Window.width,
    height: height(8),
    backgroundColor: 'transparent',
    borderBottomColor: 'white',
    borderBottomWidth: 0.5,
  },
  detailContent: {
    fontSize: Fonts.size.regular,
    color: '#1d1d1d',
    fontFamily: 'OpenSans-Regular',
  },
  detailContent1: {
    fontSize: Fonts.size.regular,
    color: 'blue',
    fontFamily: 'OpenSans-Regular',
    //left:-10
  },
  detailTitle: {
    fontSize: Fonts.size.medium,
    color: '#A6A6A6',
    fontFamily: 'OpenSans-Regular',
  },
  textbox1: {
    left: 8,
  },
  textbox2: {
    left: width(20),
  },
  textbox3: {
    left: width(33),
  },
  textbox4: {
    left: width(38),
  },
  textbox5: {
    left: width(37),
  },
  textbox6: {
    left: width(36),
  },
  textbox7: {
    left: width(30),
  },
  textbox8: {
    left: width(25),
  },
  textbox9: {
    left: width(26),
  },
  textbox10: {
    left: width(25),
  },
  card: {
    backgroundColor: 'white',
    width: width(100),
    flexDirection: 'column',
    borderBottomWidth: 0.5,
    borderBottomColor: 'lightgrey',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    padding: 5,
    paddingLeft: 20,
    marginTop: 2,
  },
  lastCard: {
    backgroundColor: 'white',
    width: width(100),
    flexDirection: 'column',
    borderTopWidth: 0.5,
    borderTopColor: 'lightgrey',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    padding: 5,
    paddingLeft: 20,
  },
  card1: {
    backgroundColor: 'white',
    width: width(100),
    flexDirection: 'column',
    borderBottomWidth: 0.5,
    borderBottomColor: 'lightgrey',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    padding: 5,
    paddingLeft: 20,
  },
  boxCard1: {
    left: 6,
    //top: 10,
  },
  boxCard2: {
    left: 7,
    paddingRight: 5,
    //marginTop: 11
  },
  speechTextBlock: {
    // alignItems: 'flex-start',
    // justifyContent: 'flex-start',
    width: '90%',
    backgroundColor: 'white',
    // margin: 10,
    elevation: 3,
    borderRadius: 5,
    // padding: 10,
    borderWidth: 0.5,
    borderColor: 'lightgrey',
    height: 30,
    padding: 4,
    // flexDirection:'row',
    margin: 5,
  },
  speechTextHead: {
    fontSize: Fonts.size.medium,
    color: '#333',
  },
  suggestionbox: {
    width: null,
    height: 40,
    backgroundColor: 'white',
    margin: 5,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    borderTopLeftRadius: 30,
    borderBottomLeftRadius: 30,
    borderWidth: 0.5,
    borderColor: 'lightgrey',
  },
  modalContainer: {
    width: '100%',
    height: '70%',
    backgroundColor: 'white',
    borderRadius: 5,
  },
  modalBody: {
    width: '100%',
    height: 50,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 0.3,
    // boderBottomColor:'lightgrey',
    flexDirection: 'row',
    top: 10,
  },
  modalFooter: {
    width: '100%',
    height: 50,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    bottom: 5,
    borderTopWidth: 0.3,
    borderTopColor: 'lightgrey',
  },
  floatingDiv: {
    position: 'absolute',
    right: 20,
    bottom: 90,
    zIndex: 1000,
    justifyContent: 'center',
    alignItems: 'center',
  },
  floatinBtn: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    width: 60,
    height: 60,
    backgroundColor: 'white',
    borderRadius: 100,
    zIndex: 1000,
    elevation: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
