import {StyleSheet, ColorPropType, Platform} from 'react-native';
import {Fonts} from '../../Themes';
import colors from '../../Themes/Colors';

export default styles = StyleSheet.create({
  mainContainer: {
    width: '100%',
    height: '100%',
  },
  welcomeTxtView: {
    maxWidth: '70%',
    marginLeft: 10,
  },
  header: {
    width: '100%',
    height: 50,
    alignItems: 'center',
    flexDirection: 'row',
  },
  headerIcon: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexDirection: 'row',
    paddingRight: 20,
  },
  welcomeTxt: {
    fontSize: Fonts.size.h6,
    color: 'white',
    fontFamily: 'OpenSans-Bold',
  },
  bellIcon: {
    minWidth: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellBadge: {
    minWidth: 16,
    height: 16,
    paddingHorizontal: 4,
    borderRadius: 8,
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 4,
    right: 4,
  },
  statusOuterView: {
    width: '100%',
    marginTop: 10,
    marginBottom: 10,
    alignItems: 'center',
    flexDirection: 'row',
    shadowColor: 'grey',
  },
  statusView: {
    flex: 1,
    height: '100%',
    margin: 5,
    paddingTop: 4,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: '#fff',
    borderRadius: 5,
    shadowOffset: {width: 5, height: 5},
    shadowColor: Platform.OS === 'ios' ? '#D3D3D3' : '#000',
    shadowOpacity: 5,
    elevation: 5,
  },
  statusheaderTxt: {
    fontSize: 30,
    color: 'grey',
    textAlign: 'center',
    fontFamily: 'OpenSans-SemiBold',
  },
  statusTxt: {
    fontSize: Fonts.size.h,
    color: 'grey',
    textAlign: 'center',
    fontFamily: 'OpenSans-Regular',
  },
  vertBorder: {
    width: 1,
    height: '75%',
    backgroundColor: 'lightgrey',
  },
  auditNotifyTxt: {
    fontSize: Fonts.size.h5,
    width: '100%',
    paddingVertical: 4,
    backgroundColor: 'white',
    textAlign: 'center',
    color: '#4ACECD',
    fontFamily: 'OpenSans-SemiBold',
  },
  showMyAll: {
    backgroundColor: 'lightgrey',
    paddingVertical: 6,
    width: '100%',
  },
  cardTitle: {
    paddingTop: 10,
    paddingBottom: 1,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'white',
  },
  cardTitleTxt: {
    fontSize: 18,
    color: 'grey',
    // fontWeight:'bold',
    fontFamily: 'OpenSans-BoldItalic',
  },
  moreTxt: {
    fontSize: 16,
    color: '#00A2E5',
    fontFamily: 'OpenSans-Regular',
  },
  cardOuterView: {
    width: '90%',
    paddingVertical: 10,
    marginLeft: '5%',
    flexDirection: 'row',
  },
  borderEnabled: {
    borderBottomWidth: 2,
    borderBottomColor: 'lightgrey',
  },
  detailsView: {
    flex: 3,
    borderLeftWidth: 4,
    paddingLeft: 8,
  },
  progressRound: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderColor: 'lightgrey',
    borderWidth: 4,
  },
  floatingDiv: {
    position: 'absolute',
    right: 20,
    bottom: 120,
    zIndex: 1000,
    justifyContent: 'center',
    alignItems: 'center',
  },
  floatinBtn: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    width: 60,
    height: 60,
    backgroundColor: '#00b3d6',
    // backgroundColor:'#4ACECD',
    borderRadius: 100,
    zIndex: 1000,
    elevation: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressVal: {
    fontSize: Fonts.size.medium,
    color: '#1d1d1d',
    fontFamily: 'OpenSans-Regular',
  },
  noActivityTxt: {
    textAlign: 'center',
    fontSize: Fonts.size.h6,
    // marginTop: 40,
    // marginBottom: 40,
    color: 'grey',
    fontFamily: 'OpenSans-Regular',
  },
  bgWhite: {
    backgroundColor: 'white',
  },
  paddingTop5: {
    paddingTop: 5,
  },
  circle: {
    flex: 1,
    marginLeft: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusTextCircle: {
    marginTop: 4,
    maxWidth: 100,
    textAlign: 'center',
    fontFamily: 'OpenSans-Regular',
  },
});
